[pytest]
DJANGO_SETTINGS_MODULE = recipesAdmin.settings
python_files = tests.py test_*.py *_tests.py
addopts = --strict-markers --doctest-modules
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    fast: marks tests as fast (deselect with '-m "not fast"')